# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Coder of Convenience
description: > # this means to ignore newlines until "baseurl:"
  This will be an experimental blog site based on Git pages.  The site was 
  built using Jekyll.  I will try to keep the content code monkey related.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gitpage.dewser.com" # the base hostname & protocol for your site
twitter_username: dewser
github_username:  TheDewser

# Build settings
markdown: kramdown
